spring:
  application:
    name: student-course-system

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_manage_system?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: yangjiachi159
    # 连接池配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: true  # 显示SQL语句
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        # 数据库表名和字段名命名策略
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    defer-datasource-initialization: true # 延迟数据源初始化，确保可以在数据库表创建完成后执行import.sql等脚本
    properties:
      hibernate:
        format_sql: true  # 格式化SQL输出
        dialect: org.hibernate.dialect.MySQLDialect
        # 启用SQL统计
        generate_statistics: false
        # 批处理大小
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

  # 安全配置
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# JWT配置
jwt:
  secret: mySecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  expiration: 86400000  # 24小时（毫秒）
  header: Authorization
  prefix: "Bearer "

# 文件上传配置
file:
  upload:
    path: uploads/courseware
    # 允许的文件类型
    allowed-types: pdf,doc,docx,ppt,pptx,xls,xlsx,txt,zip,rar,7z,mp4,avi,mov

# Swagger配置
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# 日志配置
logging:
  level:
    root: INFO
    com.example.studentcoursesystem: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 显示SQL参数
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/student-course-system.log
    max-size: 100MB
    max-history: 30

# 分页配置
spring.data.web.pageable:
  default-page-size: 20
  max-page-size: 100

# 缓存配置（如果需要）
spring.cache:
  type: simple

# 国际化配置
spring.messages:
  basename: messages
  encoding: UTF-8
  cache-duration: 3600

# 系统配置
system:
  # 选课开放时间配置
  course-selection:
    start-time: "2024-09-01 08:00:00"
    end-time: "2024-09-15 18:00:00"
  # 抽签时间配置
  lottery:
    time: "2024-09-16 10:00:00"
  # 管理员默认密码
  admin:
    default-password: admin123
  # 密码策略
  password:
    min-length: 6
    max-length: 20
    require-special-char: false

# 管理配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: when-authorized